In [9]:
import numpy as np
a=np.array([5,1,6,8,3])
a.sort()
a
b=np.random.randint(1,100,24).reshape(6,4)
print(b)
np.sort(b,axis=1)

[[95  7 38 77]
 [84 36 19 77]
 [11 63 70 51]
 [20 72 23  6]
 [84 80 92 10]
 [80 26 77 30]]


array([[ 7, 38, 77, 95],
       [19, 36, 77, 84],
       [11, 51, 63, 70],
       [ 6, 20, 23, 72],
       [10, 80, 84, 92],
       [26, 30, 77, 80]])

In [13]:
import numpy as np
a=np.array([5,1,6,8,3,4])
new=np.array_split(a,2)
new

[array([5, 1, 6]), array([8, 3, 4])]